### ISSUE TITLE
Pathfind

### ISSUE THREAD

**Issue by Ihavesoul** [RonenNess/UnityUtils#3]
Man. In Readme and in Point.cs you say use my script like this : 

You have very strange Readme. 
It is very useles scripts for Unity (if i should use this how you show it).
Grid - do you know Tilemap have the same name? 
And how i can use this A* alg for Unity? I can understand your scripts if we talk about just numbers and nothink else. But if we talk about Unity - this is scripts = wiki article.

**Comment by RonenNess** [comment]
> Grid - do you know Tilemap have the same name?

Yes, I wrote it before Unity introduced their own grid, maybe I'll fix it one day.

> And how i can use this A* alg for Unity? I can understand your scripts if we talk about just numbers and nothink else. But if we talk about Unity - this is scripts = wiki article.

Please see the readme for the A* algorithm:

https://github.com/RonenNess/UnityUtils/tree/master/Controls/PathFinding/2dTileBasedPathFinding

there are some examples there.

Thanks,
