### ISSUE TITLE
Can this A star util be used in hexagon tilemap?

### ISSUE THREAD

**Issue by pharazone** [RonenNess/UnityUtils#5]
Sorry to interrupt you again. 

This is my little question....I'm about to make a game that is based on Hexagon Tilemap. So I wonder if this beatiful util could be uesd in the hexagon tilemap system?

Thank you!

**Comment by RonenNess** [comment]
Hi @pharazone, 
Unfortunately no, it only works on a square-based grid. To make it work with hexagon you need 6 neighbors, which I don't support.

You can read more here, maybe it will help you edit the code and get what you want:

https://stackoverflow.com/questions/38015645/a-pathfinding-in-a-hexagonal-grid

(It's in js but algorithm is similar)
