### ISSUE TITLE
Memory Optimization

### ISSUE THREAD

**Issue by Bryan-Legend** [RonenNess/UnityUtils#6]
Thank you for this project. It's really great. I'm using it in my [Never Split the Party](https://store.steampowered.com/app/711810/Never_Split_the_Party/) game.

Unfortunately, it's doing a ton of unnecessary memory allocation. Something like 30k of memory for each path find in my usage. With several enemies updating their paths often it was often allocating 150k per frame!

Here's how I optimized it.

Change Point from a class to a struct. Value types are allocated on stack instead of heap. They also do better in arrays since there's no reference operation.

In PathFinding._ImpFindPath make openSet and closedSet static and just clear them instead of recreating them. That makes them non-thread safe but I'm not doing anything fancy with threads I don't think.

Changed Grid.GetNeighbours to be an IEnumerable.

`
/// <summary>
        /// Get all the neighbors of a given tile in the grid.
        /// </summary>
        /// <param name="node">Node to get neighbors for.</param>
        /// <returns>List of node neighbors.</returns>
        public IEnumerable<Node> GetNeighbours(Node node, Pathfinding.DistanceType distanceType)
        {
            int x = 0, y = 0;

            switch (distanceType)
            {
                case Pathfinding.DistanceType.Manhattan:
                    y = 0;
                    for (x = -1; x <= 1; ++x)
                    {
                        var neighbor = AddNodeNeighbour(x, y, node);
                        if (neighbor != null)
                            yield return neighbor;
                    }

                    x = 0;
                    for (y = -1; y <= 1; ++y)
                    {
                        var neighbor = AddNodeNeighbour(x, y, node);
                        if (neighbor != null)
                            yield return neighbor;
                    }
                    break;

                case Pathfinding.DistanceType.Euclidean:
                    for (x = -1; x <= 1; x++)
                    {
                        for (y = -1; y <= 1; y++)
                        {
                            var neighbor = AddNodeNeighbour(x, y, node);
                            if (neighbor != null)
                                yield return neighbor;
                        }
                    }
                    break;
            }
        }

        /// <summary>
        /// Adds the node neighbour.
        /// </summary>
        /// <returns><c>true</c>, if node neighbour was added, <c>false</c> otherwise.</returns>
        /// <param name="x">The x coordinate.</param>
        /// <param name="y">The y coordinate.</param>
        /// <param name="node">Node.</param>
        /// <param name="neighbours">Neighbours.</param>
        Node AddNodeNeighbour(int x, int y, Node node)
        {
            if (x == 0 && y == 0)
                return null;

            int checkX = node.gridX + x;
            int checkY = node.gridY + y;

            if (checkX >= 0 && checkX < gridSizeX && checkY >= 0 && checkY < gridSizeY)
            {
                return nodes[checkX, checkY];
            }

            return null;
        }
`
I might convert _ImpFindPath to be an IEnumerable as well.

**Comment by RonenNess** [comment]
Hi @Bryan-Legend , thank you for the feedback!
Your game look solid, happy to know I contributed a tiny bit to it 👍 

> Change Point from a class to a struct.

Good suggestion! done.

> In PathFinding._ImpFindPath make openSet and closedSet static and just clear them instead of recreating them.

I don't think its justified for this use case. even though clear() has the advantage of keeping the list capacity, since we're not dealing with huge lists and not calling the algorithm millions of times, it seems like overkill optimization at the expense of code beauty and thread safety (that I'm not sure exists tbh :)). If you disagree and have usecase where its critical, let me know.

> Changed Grid.GetNeighbours to be an IEnumerable.

Didn't see much diff in GC but code looks nicer, so added too :).

I also added a test project in plain C#, so feel free to experiment with it and test the algorithm with different optimizations.

Thanks!

**Comment by Bryan-Legend** [comment]
> Hi @Bryan-Legend , thank you for the feedback!
> Your game look solid, happy to know I contributed a tiny bit to it 👍
> 
> > Change Point from a class to a struct.
> 
> Good suggestion! done.
> 
> > In PathFinding._ImpFindPath make openSet and closedSet static and just clear them instead of recreating them.
> 
> I don't think its justified for this use case. even though clear() has the advantage of keeping the list capacity, since we're not dealing with huge lists and not calling the algorithm millions of times, it seems like overkill optimization at the expense of code beauty and thread safety (that I'm not sure exists tbh :)). If you disagree and have usecase where its critical, let me know.
> 
> > Changed Grid.GetNeighbours to be an IEnumerable.
> 
> Didn't see much diff in GC but code looks nicer, so added too :).
> 
> I also added a test project in plain C#, so feel free to experiment with it and test the algorithm with different optimizations.
> 
> Thanks!

As I got further with the memory profiling, it turns out that the iterators allocate objects. So each call to GetNeighbors was allocating 160 bytes. I switched it back to a static list that gets cleared. Reusing the static objects is very efficient because they stay in the CPU memory cache when you re-use the same memory over and over.

I also switched the RetracePath method to use a static list. Tried to use the Linq Reverse method with it but couldn't get it to work well. I could switch it to use a for loop but it's good enough now.

In my game, it's mostly used for having enemies navigate towards the players, who are always moving, so I have to path find quite often.  There's also walls and other obstacles that can move or get exploded. Add a few dozen enemies and it can get pretty crazy.

**Comment by RonenNess** [comment]
Could you post your code so I can examine it and compare?

> In my game, it's mostly used for having enemies navigate towards the players, who are always moving, so I have to path find quite often. There's also walls and other obstacles that can move or get exploded. Add a few dozen enemies and it can get pretty crazy.

But your rooms are pretty small and there are only active rooms as the max number of players right? This should greatly optimize your pathfind. Also I think for your game's pace its ok to reroute once every half a second. Just some thoughts for improvements, if you haven't done them already :)

Thanks

**Comment by Bryan-Legend** [comment]
I also renamed _ImpFindPath to FindNodePath and exposed it. Calling it directly and working with Nodes in my game avoids converting them to Points and saves work in my case. If that list got saved by a caller it'd be bad though.

Thanks again for the very helpful code.

Here's the grid code.
```C#
        List<Node> neighbors = new List<Node>();
        /// <summary>
        /// Get all the neighbors of a given tile in the grid.
        /// </summary>
        /// <param name="node">Node to get neighbors for.</param>
        /// <returns>List of node neighbors.</returns>
        public List<Node> GetNeighbours(Node node, Pathfinding.DistanceType distanceType)
        {
            neighbors.Clear();
            int x = 0, y = 0;

            switch (distanceType)
            {
                case Pathfinding.DistanceType.Manhattan:
                    y = 0;
                    for (x = -1; x <= 1; ++x)
                    {
                        var neighbor = AddNodeNeighbour(x, y, node);
                        if (neighbor != null)
                            neighbors.Add(neighbor);
                    }

                    x = 0;
                    for (y = -1; y <= 1; ++y)
                    {
                        var neighbor = AddNodeNeighbour(x, y, node);
                        if (neighbor != null)
                            neighbors.Add(neighbor);
                    }
                    break;

                case Pathfinding.DistanceType.Euclidean:
                    for (x = -1; x <= 1; x++)
                    {
                        for (y = -1; y <= 1; y++)
                        {
                            var neighbor = AddNodeNeighbour(x, y, node);
                            if (neighbor != null)
                                neighbors.Add(neighbor);
                        }
                    }
                    break;
            }

            return neighbors;
        }

        /// <summary>
        /// Adds the node neighbour.
        /// </summary>
        /// <returns><c>true</c>, if node neighbour was added, <c>false</c> otherwise.</returns>
        /// <param name="x">The x coordinate.</param>
        /// <param name="y">The y coordinate.</param>
        /// <param name="node">Node.</param>
        /// <param name="neighbours">Neighbours.</param>
        Node AddNodeNeighbour(int x, int y, Node node)
        {
            if (x == 0 && y == 0)
                return null;

            int checkX = node.gridX + x;
            int checkY = node.gridY + y;

            if (checkX >= 0 && checkX < gridSizeX && checkY >= 0 && checkY < gridSizeY)
            {
                return nodes[checkX, checkY];
            }

            return null;
        }
```

Here's the PathFinding code
```C#
        static List<Node> openSet = new List<Node>();
        static HashSet<Node> closedSet = new HashSet<Node>();

        /// <summary>
        /// Internal function that implements the path-finding algorithm.
        /// </summary>
        /// <param name="grid">Grid to search.</param>
        /// <param name="startPos">Starting position.</param>
        /// <param name="targetPos">Ending position.</param>
        /// <param name="distance">The type of distance, Euclidean or Manhattan.</param>
        /// <param name="ignorePrices">If true, will ignore tile price (how much it "cost" to walk on).</param>
        /// <returns>List of grid nodes that represent the path to walk.</returns>
        public static IEnumerable<Node> FindNodePath(Grid grid, Point startPos, Point targetPos, DistanceType distance = DistanceType.Euclidean, bool ignorePrices = false)
        {
            Node startNode = grid.nodes[startPos.x, startPos.y];
            Node targetNode = grid.nodes[targetPos.x, targetPos.y];

            openSet.Clear();
            closedSet.Clear();

            openSet.Add(startNode);

            while (openSet.Count > 0)
            {
                Node currentNode = openSet[0];
                for (int i = 1; i < openSet.Count; i++)
                {
                    if (openSet[i].fCost < currentNode.fCost || openSet[i].fCost == currentNode.fCost && openSet[i].hCost < currentNode.hCost)
                    {
                        currentNode = openSet[i];
                    }
                }

                openSet.Remove(currentNode);
                closedSet.Add(currentNode);

                if (currentNode == targetNode)
                {
                    return RetracePath(grid, startNode, targetNode);
                }

                foreach (Node neighbour in grid.GetNeighbours(currentNode, distance))
                {
                    if (!neighbour.walkable || closedSet.Contains(neighbour))
                    {
                        continue;
                    }

                    int newMovementCostToNeighbour = currentNode.gCost + GetDistance(currentNode, neighbour) * (ignorePrices ? 1 : (int)(10.0f * neighbour.price));
                    if (newMovementCostToNeighbour < neighbour.gCost || !openSet.Contains(neighbour))
                    {
                        neighbour.gCost = newMovementCostToNeighbour;
                        neighbour.hCost = GetDistance(neighbour, targetNode);
                        neighbour.parent = currentNode;

                        if (!openSet.Contains(neighbour))
                            openSet.Add(neighbour);
                    }
                }
            }

            path.Clear();
            return path;
        }

        static List<Node> path = new List<Node>();

        /// <summary>
        /// Retrace path between two points.
        /// </summary>
        /// <param name="grid">Grid to work on.</param>
        /// <param name="startNode">Starting node.</param>
        /// <param name="endNode">Ending (target) node.</param>
        /// <returns>Retraced path between nodes.</returns>
        private static IEnumerable<Node> RetracePath(Grid grid, Node startNode, Node endNode)
        {
            path.Clear();
            Node currentNode = endNode;

            while (currentNode != startNode)
            {
                path.Add(currentNode);
                currentNode = currentNode.parent;
            }
            path.Reverse();
            return path;
        }
```

**Comment by Bryan-Legend** [comment]
Looking at the code more it looks like the PathFinding methods could be moved into the Grid class.

In my code I'm converting the nodes to and from Vector3 position at the center of each tile using these.

```c#
        PathFind.Point ToPoint(Vector3 position)
        {
            position -= transform.position;
            position -= new Vector3(0.25f, 0.25f);
            position /= 0.5f;
            return new PathFind.Point(
                Math.Max(0, Math.Min((int)Math.Round(position.x) + (TileWidth / 2), TileWidth - 1)),
                Math.Max(0, Math.Min((int)Math.Round(position.y) + (TileHeight / 2), TileHeight - 1))
            );
        }

        Vector3 ToPosition(PathFind.Point point)
        {
            return new Vector3((point.x - (TileWidth / 2)) * 0.5f + 0.25f, (point.y - (TileHeight / 2)) * 0.5f + 0.25f) + transform.position;
        }

        Vector3 ToPosition(PathFind.Node node)
        {
            return new Vector3((node.gridX - (TileWidth / 2)) * 0.5f + 0.25f, (node.gridY - (TileHeight / 2)) * 0.5f + 0.25f) + transform.position;
        }
```
