### ISSUE TITLE
Too stupid to set up

### ISSUE THREAD

**Issue by Biebras** [RonenNess/UnityUtils#7]
I was looking at this code I can't figure out how to do it. I copied all file, but then I'm completely stuck, can you give me more info?

Width and height and other variables are not foud...

Edit: This is for pathfinding 2d A*

**Comment by RonenNess** [comment]
Did you read the instructions?

https://github.com/RonenNess/UnityUtils/blob/master/Controls/PathFinding/2dTileBasedPathFinding/README.md

What did you not understand there?

**Comment by Biebras** [comment]
Yeah, I read the instructions. So I start by adding PathFinding script to my project and other scripts, but then I'm lost cause I don't have monobehavior script, so I tried to create my own, by adding these lines.

```
// create the tiles map
float[,] tilesmap = new float[width, height];
// set values here....
// every float in the array represent the cost of passing the tile at that position.
// use 0.0f for blocking tiles.

// create a grid
PathFind.Grid grid = new PathFind.Grid(tilesmap);

// create source and target points
PathFind.Point _from = new PathFind.Point(1, 1);
PathFind.Point _to = new PathFind.Point(10, 10);

// get path
// path will either be a list of Points (x, y), or an empty list if no path is found.
List<PathFind.Point> path = PathFind.Pathfinding.FindPath(grid, _from, _to);

// for Manhattan distance
List<PathFind.Point> path = PathFind.Pathfinding.FindPath(grid, _from, _to, Pathfinding.DistanceType.Manhattan);
```

But half of the commands goes red...

**Comment by RonenNess** [comment]
Not sure what you did there exactly but you can't have code floating around outside classes / methods. Unity makes it very easy to create script components, I recommend you take a look at their basic video tutorials they will clear things up for you.

Closing this issue as it's not really a bug / issue.
Thanks,
